tweebank_labels_to_ids = {
    'PUNCT' : 0, 
    'NUM' : 1, 
    'VERB' : 2, 
    'DET' : 3, 
    'PROPN' : 4, 
    'PRON' : 5, 
    'ADJ' : 6, 
    'ADP' : 7, 
    'SYM' : 8, 
    'CCONJ' : 9, 
    'NOUN' : 10, 
    'INTJ' : 11, 
    'AUX' : 12, 
    'PART' : 13, 
    'ADV' : 14, 
    'SCONJ' : 15,
    'X' : 16,
}

ner_labels_to_ids = {
    'B-PER' : 0,
    'I-PER' : 1,
    'B-ORG' : 2,
    'I-ORG' : 3,
    'B-LOC' : 4, 
    'I-LOC' : 5,
    'B-MISC' : 6,
    'I-MISC' : 7, 
    'O' : 8,   
}